<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">


	<modelVersion>4.0.0</modelVersion>
	<groupId>com.biit</groupId>
	<artifactId>orbeon-form-reader</artifactId>
	<packaging>jar</packaging>
	<version>0.7.15</version>
	<name>Orbeon Form Reader</name>

	<distributionManagement>
		<repository>
			<id>central</id>
			<name>biit-releases</name>
			<url>https://git.biit-solutions.com:8443/artifactory/ext-release-local</url>
		</repository>
		<snapshotRepository>
			<id>snapshots</id>
			<name>libs-snapshot</name>
			<url>https://git.biit-solutions.com:8443/artifactory/libs-snapshot</url>
		</snapshotRepository>
	</distributionManagement>

	<scm>
		<connection>scm:git:git.biit-solutions.com:OrbeonFormsReader.git</connection>
		<developerConnection>scm:git:git.biit-solutions.com:OrbeonFormsReader.git</developerConnection>
		<tag>orbeon-form-reader-0.7.15</tag>
	</scm>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven-compiler-plugin.version>3.1</maven-compiler-plugin.version>
		<maven-antrun-plugin.version>1.7</maven-antrun-plugin.version>
		<maven-surefire.version>2.14.1</maven-surefire.version>
		<jaxen.version>1.1.6</jaxen.version>
		<dom4j.version>1.6.1</dom4j.version>
		<org.testng.version>6.8.8</org.testng.version>
		<maven-resources-plugin.version>2.7</maven-resources-plugin.version>
		<maven-release-plugin.version>2.5.1</maven-release-plugin.version>
		<maven-scm-provider-gitexe.version>1.9.2</maven-scm-provider-gitexe.version>
		<project.scm.id>git</project.scm.id>
		<!-- BiiT dependencies -->
		<biit-common-utils.version>[0.4,0.5)</biit-common-utils.version>
		<biit-form-submitted.version>[0.2,0.3)</biit-form-submitted.version>
	</properties>

	<dependencies>
		<!-- For reading XML -->
		<dependency>
			<groupId>dom4j</groupId>
			<artifactId>dom4j</artifactId>
			<version>${dom4j.version}</version>
		</dependency>
		<dependency>
			<groupId>jaxen</groupId>
			<artifactId>jaxen</artifactId>
			<version>${jaxen.version}</version>
		</dependency>
		<!-- File access -->
		<dependency>
			<groupId>com.biit</groupId>
			<artifactId>common-utils</artifactId>
			<version>${biit-common-utils.version}</version>
		</dependency>
		<dependency>
			<groupId>com.biit</groupId>
			<artifactId>form-structure-submitted</artifactId>
			<version>${biit-form-submitted.version}</version>
		</dependency>
		<!-- Testing -->
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>${org.testng.version}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${maven-compiler-plugin.version}</version>
				<configuration>
					<source>7</source>
					<target>7</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>${maven-surefire.version}</version>
				<configuration>
					<useFile>false</useFile>
					<trimStackTrace>false</trimStackTrace>
					<suiteXmlFiles>
						<suiteXmlFile>src/test/config/testng.xml</suiteXmlFile>
					</suiteXmlFiles>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<version>${maven-resources-plugin.version}</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-release-plugin</artifactId>
				<version>${maven-release-plugin.version}</version>
				<dependencies>
					<dependency>
						<groupId>org.apache.maven.scm</groupId>
						<artifactId>maven-scm-provider-gitexe</artifactId>
						<version>${maven-scm-provider-gitexe.version}</version>
					</dependency>
				</dependencies>
				<configuration>
					<checkModificationExcludes>
						<checkModificationExclude>pom.xml</checkModificationExclude>
					</checkModificationExcludes>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
